FROM nginx:alpine
COPY /dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


# Created using https://dev.to/mubbashir10/containerize-react-app-with-docker-for-production-572b
# and https://www.dailysmarty.com/posts/steps-for-deploying-a-static-html-site-with-docker-and-nginx
# No need to build nodejs since it is included in the index.html.